# Schema for the configuration files of the website_speed module.
website_speed.settings:
  type: config_object
  label: 'Website Speed settings'
  mapping:
    enable_tracking:
      type: boolean
      label: 'Enable tracking of Website Speed'
    use_terminate_time:
      type: boolean
      label: 'Use Terminate time to calculate page speed'
    items_per_table:
      type: integer
      label: 'Number of rows in Top X tables'